import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.105.0'

const SUPABASE_URL='https://zeyvkuhqgbqjqalxubrq.supabase.co'
const SUPABASE_KEY='sb_publishable_trF3YpEfBC7rMZpxs0lzzg_utxyNU7t'
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY)
const $=id=>document.getElementById(id)
const state={user:null,membership:null,session:null,scene:null,tokens:[],controllers:[],channel:null,scale:1,panX:30,panY:30,pointers:new Map(),drag:null,pan:null}
const views=['authView','lobbyView','tableView']
function show(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id))}
function msg(id,text,bad=false){$(id).textContent=text||'';$(id).style.color=bad?'#ff7078':''}
function feed(text){const el=document.createElement('div');el.className='feed-entry';el.textContent=text;$('feed').prepend(el);while($('feed').children.length>12)$('feed').lastChild.remove()}
function code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join('')}

async function boot(){const {data:{session}}=await supabase.auth.getSession();if(session)await signedIn(session.user);supabase.auth.onAuthStateChange(async(_,s)=>{if(s?.user&&!state.user)await signedIn(s.user);if(!s){state.user=null;show('authView')}})}
async function signedIn(user){state.user=user;$('signOutBtn').classList.remove('hidden');$('connectionBadge').textContent='LINKED';$('connectionBadge').classList.add('live');show('lobbyView');await loadLobby()}

$('signInBtn').onclick=async()=>{msg('authMessage','LINKING…');const {error}=await supabase.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});msg('authMessage',error?error.message:'CONNECTED',!!error)}
$('signUpBtn').onclick=async()=>{msg('authMessage','CREATING IDENTITY…');const {data,error}=await supabase.auth.signUp({email:$('email').value.trim(),password:$('password').value,options:{data:{display_name:$('displayName').value.trim()}}});if(error)return msg('authMessage',error.message,true);msg('authMessage',data.session?'ACCOUNT CREATED':'Check your email to confirm the account, then sign in.')}
$('signOutBtn').onclick=async()=>{leaveRealtime();await supabase.auth.signOut();$('signOutBtn').classList.add('hidden');$('connectionBadge').textContent='OFFLINE';$('connectionBadge').classList.remove('live')}

async function loadLobby(){if(!state.user)return;const {data:members,error}=await supabase.from('campaign_members').select('campaign_id,role,display_name,campaigns(id,name),game_sessions(id,name,join_code,is_active)').eq('user_id',state.user.id);if(error){msg('lobbyMessage',error.message,true);return}const gm=$('gmCampaigns'),pl=$('playerCampaigns');gm.innerHTML='';pl.innerHTML='';for(const m of members||[]){const sessions=(m.game_sessions||[]).filter(s=>s.is_active);for(const s of sessions){const card=document.createElement('div');card.className='campaign-card';card.innerHTML=`<div><strong>${escapeHtml(m.campaigns?.name||'Campaign')}</strong><small>${escapeHtml(s.name)} · ${s.join_code}</small></div>`;const b=document.createElement('button');b.textContent='ENTER';b.onclick=()=>enterSession(s.id,m.role);card.appendChild(b);(m.role==='gm'?gm:pl).appendChild(card)}}}

$('createDemoBtn').onclick=async()=>{msg('lobbyMessage','BUILDING TEST TABLE…');$('createDemoBtn').disabled=true;try{const {data:campaignId,error:e1}=await supabase.rpc('bootstrap_campaign',{campaign_name:'Destiny'});if(e1)throw e1;const join=code();const {data:sess,error:e2}=await supabase.from('game_sessions').insert({campaign_id:campaignId,name:'Tactical Link Test',join_code:join,is_active:true}).select().single();if(e2)throw e2;const {data:scene,error:e3}=await supabase.from('scenes').insert({session_id:sess.id,name:'Industrial Docking Bay',grid_cols:30,grid_rows:20,grid_size:64,is_active:true}).select().single();if(e3)throw e3;const names=['Kaia Freestar','Kad Trayla','Darius Voss','Karrsk Thorsa'];const {data:chars,error:e4}=await supabase.from('characters').insert(names.map(name=>({campaign_id:campaignId,name,kind:'pc'}))).select();if(e4)throw e4;const {error:e5}=await supabase.from('scene_tokens').insert(chars.map((c,i)=>({scene_id:scene.id,character_id:c.id,label:c.name,kind:'pc',x:4+i*3,y:8+(i%2)*3,size_squares:1,state:{hp:null}})));if(e5)throw e5;msg('lobbyMessage',`TEST TABLE READY · JOIN CODE ${join}`);await loadLobby();await enterSession(sess.id,'gm')}catch(e){msg('lobbyMessage',e.message,true)}finally{$('createDemoBtn').disabled=false}}

$('joinBtn').onclick=async()=>{const join=$('joinCode').value.trim().toUpperCase();if(join.length<4)return msg('lobbyMessage','Enter a valid join code.',true);let display=$('displayName').value.trim()||state.user?.user_metadata?.display_name||state.user?.email?.split('@')[0]||'Player';const {data,error}=await supabase.rpc('join_game_session',{p_join_code:join,p_display_name:display});if(error)return msg('lobbyMessage',error.message,true);msg('lobbyMessage',`LINKED TO ${data?.[0]?.campaign_name||'CAMPAIGN'}`);await loadLobby();if(data?.[0])await enterSession(data[0].session_id,'player')}

async function enterSession(sessionId,role){state.membership={role};const {data:sess,error}=await supabase.from('game_sessions').select('id,name,join_code,campaign_id').eq('id',sessionId).single();if(error)return msg('lobbyMessage',error.message,true);const {data:scenes}=await supabase.from('scenes').select('*').eq('session_id',sessionId).eq('is_active',true).order('sort_order').limit(1);if(!scenes?.length)return msg('lobbyMessage','No active scene.',true);state.session=sess;state.scene=scenes[0];$('sessionName').textContent=sess.name;$('roleLabel').textContent=role.toUpperCase();$('codeLabel').textContent=sess.join_code;$('sceneName').textContent=state.scene.name;$('gridLabel').textContent=`${state.scene.grid_cols} × ${state.scene.grid_rows}`;show('tableView');await loadTokens();setupWorld();subscribeRealtime();feed(`Connected as ${role.toUpperCase()}.`)}

async function loadTokens(){const {data:tokens,error}=await supabase.from('scene_tokens').select('*').eq('scene_id',state.scene.id).order('z_index');if(error){feed(error.message);return}state.tokens=tokens||[];const ids=state.tokens.map(t=>t.id);state.controllers=[];if(ids.length){const {data}=await supabase.from('token_controllers').select('*').in('token_id',ids);state.controllers=data||[]}renderTokens()}
function canMove(t){return state.membership?.role==='gm'||(!t.locked&&state.controllers.some(c=>c.token_id===t.id&&c.user_id===state.user.id))}
function isMine(t){return state.controllers.some(c=>c.token_id===t.id&&c.user_id===state.user.id)}
function setupWorld(){const s=state.scene,w=$('world'),size=s.grid_size;w.style.width=`${s.grid_cols*size}px`;w.style.height=`${s.grid_rows*size}px`;$('gridLayer').style.backgroundSize=`${size}px ${size}px`;resetView()}
function renderTokens(){const layer=$('tokenLayer'),list=$('tokenList');layer.innerHTML='';list.innerHTML='';const size=state.scene.grid_size;for(const t of state.tokens){if(state.membership?.role==='player'&&t.hidden===true)continue;const el=document.createElement('div');el.className=`token ${t.kind}${canMove(t)?'':' locked'}`;el.dataset.id=t.id;const px=size*Number(t.size_squares);el.style.width=`${px-8}px`;el.style.height=`${px-8}px`;el.style.left=`${Number(t.x)*size+4}px`;el.style.top=`${Number(t.y)*size+4}px`;el.style.zIndex=t.z_index;el.innerHTML=`<span class="initials">${initials(t.label)}</span><span class="token-name">${escapeHtml(t.label)}</span>`;el.onpointerdown=e=>tokenDown(e,t);layer.appendChild(el);const row=document.createElement('div');row.className='token-row';row.innerHTML=`<span>${escapeHtml(t.label)}</span><span class="${isMine(t)?'you':''}">${isMine(t)?'YOU':canMove(t)?'GM':'—'}</span>`;if(state.membership?.role==='player'&&t.kind==='pc'&&!isMine(t)){row.style.cursor='pointer';row.title='Claim this character';row.onclick=()=>claim(t)}list.appendChild(row)}}
async function claim(t){const {data,error}=await supabase.rpc('claim_player_token',{p_token_id:t.id});if(error)return feed(error.message);if(!data)return feed(`${t.label} is already controlled by another player.`);feed(`Control linked: ${t.label}`);await loadTokens()}

function tokenDown(e,t){if(!canMove(t))return;e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);state.drag={id:t.id,el:e.currentTarget,pointer:e.pointerId};e.currentTarget.style.cursor='grabbing'}
async function tokenUp(e){if(!state.drag||e.pointerId!==state.drag.pointer)return;const t=state.tokens.find(x=>x.id===state.drag.id),el=state.drag.el,size=state.scene.grid_size;const x=Math.max(0,Math.min(state.scene.grid_cols-Number(t.size_squares),Math.round(parseFloat(el.style.left)/size)));const y=Math.max(0,Math.min(state.scene.grid_rows-Number(t.size_squares),Math.round(parseFloat(el.style.top)/size)));el.style.left=`${x*size+4}px`;el.style.top=`${y*size+4}px`;state.drag=null;const {error}=await supabase.from('scene_tokens').update({x,y}).eq('id',t.id);if(error){feed(`MOVE REJECTED: ${error.message}`);await loadTokens()}else feed(`${t.label} → ${x}, ${y}`)}
function pointerMove(e){if(state.drag&&e.pointerId===state.drag.pointer){const rect=$('world').getBoundingClientRect(),size=state.scene.grid_size;state.drag.el.style.left=`${(e.clientX-rect.left)/state.scale-size/2}px`;state.drag.el.style.top=`${(e.clientY-rect.top)/state.scale-size/2}px`;return}if(state.pan&&e.pointerId===state.pan.id){state.panX=state.pan.startX+(e.clientX-state.pan.x);state.panY=state.pan.startY+(e.clientY-state.pan.y);applyTransform()}}
function viewportDown(e){if(e.target.closest('.token'))return;state.pan={id:e.pointerId,x:e.clientX,y:e.clientY,startX:state.panX,startY:state.panY};$('viewport').setPointerCapture(e.pointerId);$('viewport').classList.add('panning')}
function viewportUp(e){if(state.pan?.id===e.pointerId){state.pan=null;$('viewport').classList.remove('panning')}tokenUp(e)}
function applyTransform(){$('world').style.transform=`translate(${state.panX}px,${state.panY}px) scale(${state.scale})`;$('zoomReadout').textContent=`${Math.round(state.scale*100)}%`}
function resetView(){const v=$('viewport'),w=state.scene.grid_cols*state.scene.grid_size,h=state.scene.grid_rows*state.scene.grid_size;state.scale=Math.min(.95,(v.clientWidth-40)/w,(v.clientHeight-40)/h);state.scale=Math.max(.2,state.scale);state.panX=(v.clientWidth-w*state.scale)/2;state.panY=(v.clientHeight-h*state.scale)/2;applyTransform()}
$('viewport').addEventListener('pointerdown',viewportDown);$('viewport').addEventListener('pointermove',pointerMove);$('viewport').addEventListener('pointerup',viewportUp);$('viewport').addEventListener('pointercancel',viewportUp);$('viewport').addEventListener('wheel',e=>{e.preventDefault();const old=state.scale;state.scale=Math.max(.2,Math.min(2.5,state.scale*(e.deltaY<0?1.1:.9)));const r=$('viewport').getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;state.panX=mx-(mx-state.panX)*(state.scale/old);state.panY=my-(my-state.panY)*(state.scale/old);applyTransform()},{passive:false})
$('resetViewBtn').onclick=resetView;$('backLobbyBtn').onclick=()=>{leaveRealtime();show('lobbyView');loadLobby()};$('copyJoinBtn').onclick=async()=>{await navigator.clipboard.writeText(state.session.join_code);feed('Join code copied.')}

function subscribeRealtime(){leaveRealtime();state.channel=supabase.channel(`scene:${state.scene.id}`).on('postgres_changes',{event:'*',schema:'public',table:'scene_tokens',filter:`scene_id=eq.${state.scene.id}`},payload=>{if(payload.eventType==='DELETE')state.tokens=state.tokens.filter(t=>t.id!==payload.old.id);else{const i=state.tokens.findIndex(t=>t.id===payload.new.id);if(i>=0)state.tokens[i]=payload.new;else state.tokens.push(payload.new)}renderTokens();if(payload.eventType==='UPDATE')feed(`${payload.new.label} synchronized.`)}).on('postgres_changes',{event:'*',schema:'public',table:'token_controllers'},()=>loadTokens()).subscribe(status=>{if(status==='SUBSCRIBED')feed('Realtime tactical link established.')})}
function leaveRealtime(){if(state.channel){supabase.removeChannel(state.channel);state.channel=null}}
function initials(s){return s.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.addEventListener('resize',()=>{if(state.scene&&!$('tableView').classList.contains('hidden'))resetView()})
boot()
