// Synchronized scene turn state; scene updates are GM-only under existing RLS.
import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.105.0';
const db=createClient('https://zeyvkuhqgbqjqalxubrq.supabase.co','sb_publishable_trF3YpEfBC7rMZpxs0lzzg_utxyNU7t');
const order=document.getElementById('combatOrder'),layer=document.getElementById('tokenLayer'),role=document.getElementById('roleLabel');
const panel=document.createElement('section');panel.className='combat-turn-panel';panel.innerHTML='<div class="panel-title">TURN CONTROL</div><div id="turnStatus" role="status" aria-live="polite">Waiting for scene…</div><div id="turnButtons"><button type="button" id="turnStart">START / RESTART</button><button type="button" id="turnPrevious">PREVIOUS</button><button type="button" id="turnNext">NEXT TURN</button><button type="button" id="turnEnd">END COMBAT</button></div><div id="turnMessage" role="status" aria-live="polite"></div>';order.parentElement.insertBefore(panel,order);const status=panel.querySelector('#turnStatus'),buttons=panel.querySelector('#turnButtons'),message=panel.querySelector('#turnMessage');const start=panel.querySelector('#turnStart'),previous=panel.querySelector('#turnPrevious'),next=panel.querySelector('#turnNext'),end=panel.querySelector('#turnEnd');
let sceneId=null,scene=null,channel=null,loading=false,saving=false,version=0;
const gm=()=>role.textContent.trim().toLowerCase()==='gm';
function ordered(){return [...order.querySelectorAll('.combat-row')].map(row=>{const label=row.querySelector('strong')?.textContent;const token=[...layer.querySelectorAll('.token[data-id]')].find(el=>el.querySelector('.token-name')?.textContent===label);return token?.dataset.id||null}).filter(Boolean)}
function paint(){buttons.hidden=!gm();const ids=ordered();const active=scene?.combat_active_token;const index=ids.indexOf(active);const name=index<0?'—':order.querySelectorAll('.combat-row')[index]?.querySelector('strong')?.textContent||'—';const round=Number(scene?.combat_round||0);status.textContent=round>0?`ROUND ${round} · ACTIVE: ${name}`:'Combat not started';previous.disabled=next.disabled=round===0||!ids.length;start.disabled=!ids.length;end.disabled=round===0;for(const row of order.querySelectorAll('.combat-row'))row.style.background='';if(index>=0){const row=order.querySelectorAll('.combat-row')[index];if(row)row.style.background='rgba(114,201,232,.16)';}}
async function connect(){if(loading)return;const token=layer.querySelector('.token[data-id]');if(!token){paint();return;}loading=true;const request=++version;try{const {data:t,error:te}=await db.from('scene_tokens').select('scene_id').eq('id',token.dataset.id).single();if(te)throw te;if(request!==version)return;if(sceneId===t.scene_id){paint();return;}if(channel){await db.removeChannel(channel);channel=null;}sceneId=t.scene_id;const {data,error}=await db.from('scenes').select('id,combat_round,combat_active_token').eq('id',sceneId).single();if(error)throw error;scene=data;channel=db.channel(`combat-turns:${sceneId}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'scenes',filter:`id=eq.${sceneId}`},payload=>{if(payload.new.id===sceneId){scene=payload.new;paint();}}).subscribe();message.textContent='';paint();}catch(e){message.textContent=`Turn controls: ${e.message}`;}finally{loading=false;}}
async function change(kind){if(!gm()||saving||!sceneId)return;const ids=ordered();if(!ids.length&&kind!=='end')return;saving=true;for(const b of buttons.querySelectorAll('button'))b.disabled=true;message.textContent='Saving turn…';try{const {data:latest,error:readError}=await db.from('scenes').select('combat_round,combat_active_token').eq('id',sceneId).single();if(readError)throw readError;let round=Number(latest.combat_round||0),active=latest.combat_active_token;const i=ids.indexOf(active);if(kind==='start'){round=1;active=ids[0];}else if(kind==='end'){round=0;active=null;}else if(kind==='next'){if(round===0){round=1;active=ids[0];}else if(i<0){active=ids[0];}else{active=ids[(i+1)%ids.length];if(i===ids.length-1)round++;}}else if(kind==='previous'){if(round===0)return;if(i<0)active=ids[0];else if(i===0){if(round>1){round--;active=ids[ids.length-1];}}else active=ids[i-1];}const {data,error}=await db.from('scenes').update({combat_round:round,combat_active_token:active}).eq('id',sceneId).select('id,combat_round,combat_active_token').single();if(error)throw error;if(!data)throw Error('Turn update was not permitted.');scene=data;message.textContent='';paint();}catch(e){message.textContent=`Turn update failed: ${e.message}`;}finally{saving=false;paint();}}
start.onclick=()=>change('start');previous.onclick=()=>change('previous');next.onclick=()=>change('next');end.onclick=()=>change('end');
new MutationObserver(()=>{connect();paint();}).observe(layer,{childList:true});new MutationObserver(paint).observe(order,{childList:true});new MutationObserver(paint).observe(role,{childList:true,subtree:true,characterData:true});connect();
