// Destiny Tactical Table combat tracker: token combat statistics are stored in scene_tokens.state.
import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.105.0';
const db=createClient('https://zeyvkuhqgbqjqalxubrq.supabase.co','sb_publishable_trF3YpEfBC7rMZpxs0lzzg_utxyNU7t');
const list=document.getElementById('tokenList'),layer=document.getElementById('tokenLayer'),role=document.getElementById('roleLabel');
const panel=document.createElement('section');panel.className='combat-panel';panel.innerHTML=`<div class="panel-title">COMBAT TRACKER</div><div id="combatOrder"></div><div id="combatEditor"><label>TOKEN <select id="combatToken"><option value="">Select a token</option></select></label><label>INITIATIVE <input id="combatInit" type="number" step="1" placeholder="Not rolled"></label><label>CURRENT HP <input id="combatHp" type="number" step="1" placeholder="Not set"></label><label>MAX HP <input id="combatMax" type="number" min="0" step="1" placeholder="Not set"></label><label>CONDITION <select id="combatCondition"><option value="0">Normal</option><option value="-1">−1 step (−1)</option><option value="-2">−2 steps (−2)</option><option value="-3">−3 steps (−5)</option><option value="-4">−4 steps (−10)</option><option value="-5">Helpless</option></select></label><button type="button" id="combatSave">SAVE COMBAT STATS</button><div id="combatMessage" role="status" aria-live="polite"></div></div>`;
list.parentElement.appendChild(panel);
const order=panel.querySelector('#combatOrder'),editor=panel.querySelector('#combatEditor'),pick=panel.querySelector('#combatToken'),init=panel.querySelector('#combatInit'),hp=panel.querySelector('#combatHp'),max=panel.querySelector('#combatMax'),condition=panel.querySelector('#combatCondition'),save=panel.querySelector('#combatSave'),message=panel.querySelector('#combatMessage');
const isGm=()=>role.textContent.trim().toLowerCase()==='gm';
let records=[],busy=false,activeId=null;
const numberOrNull=v=>v.trim()===''?null:Number(v);
const conditionName=n=>({'0':'Normal','-1':'−1','-2':'−2','-3':'−5','-4':'−10','-5':'Helpless'})[String(n)]||'Normal';
function render(){editor.hidden=!isGm();const selected=pick.value;pick.replaceChildren(new Option('Select a token',''));for(const t of records)pick.add(new Option(t.label,t.id));pick.value=records.some(t=>t.id===selected)?selected:'';order.replaceChildren();const sorted=[...records].sort((a,b)=>{const ai=a.state?.initiative,bi=b.state?.initiative;return (bi==null?-Infinity:Number(bi))-(ai==null?-Infinity:Number(ai))||a.label.localeCompare(b.label)});for(const t of sorted){const row=document.createElement('div');row.className='combat-row';const s=t.state||{};const label=document.createElement('strong');label.textContent=t.label;const detail=document.createElement('span');detail.textContent=`INIT ${s.initiative??'—'} · HP ${s.hp??'—'}/${s.max_hp??'—'} · ${conditionName(s.condition_step??0)}`;row.append(label,detail);if(activeId===t.id)row.style.outline='1px solid #72c9e8';if(isGm()){row.style.cursor='pointer';row.addEventListener('click',()=>{pick.value=t.id;fill()})}order.append(row)}if(!sorted.length)order.textContent='No tokens in this scene.';}
function fill(){const t=records.find(x=>x.id===pick.value),s=t?.state||{};init.value=s.initiative??'';hp.value=s.hp??'';max.value=s.max_hp??'';condition.value=String(s.condition_step??0);message.textContent='';activeId=t?.id||null;render();}
pick.addEventListener('change',fill);
async function refresh(){if(busy||!isGm()&&document.getElementById('tableView').classList.contains('hidden'))return;const ids=[...layer.querySelectorAll('.token[data-id]')].map(e=>e.dataset.id);if(!ids.length){records=[];render();return}const {data,error}=await db.from('scene_tokens').select('id,label,state').in('id',ids);if(error){message.textContent=error.message;return}records=data||[];render()}
const observer=new MutationObserver(()=>{if(!busy)refresh()});observer.observe(layer,{childList:true});observer.observe(role,{childList:true,subtree:true,characterData:true});refresh();
layer.addEventListener('pointerdown',e=>{if(!isGm())return;const token=e.target.closest('.token[data-id]');if(token&&records.some(t=>t.id===token.dataset.id)){pick.value=token.dataset.id;fill()}},true);
save.addEventListener('click',async()=>{if(!isGm()||!pick.value||busy)return;const id=pick.value,initiative=numberOrNull(init.value),current=numberOrNull(hp.value),maximum=numberOrNull(max.value),step=Number(condition.value);if([initiative,current,maximum].some(n=>n!==null&&!Number.isSafeInteger(n))||maximum!==null&&maximum<0||current!==null&&current<0||current!==null&&maximum!==null&&current>maximum||![-5,-4,-3,-2,-1,0].includes(step)){message.textContent='Enter whole numbers; HP must be between 0 and maximum HP.';return}busy=true;save.disabled=true;message.textContent='Saving…';try{const {data:latest,error:readError}=await db.from('scene_tokens').select('state').eq('id',id).single();if(readError)throw readError;const state={...(latest.state||{}),initiative,hp:current,max_hp:maximum,condition_step:step};const {data,error}=await db.from('scene_tokens').update({state}).eq('id',id).select('id').single();if(error)throw error;if(!data)throw Error('Update was not permitted.');message.textContent='Combat stats saved.';}catch(e){message.textContent=`Save failed: ${e.message}`;}finally{busy=false;save.disabled=false;await refresh();pick.value=id;}});
