// Modular rooms and corridors share the scene's square coordinates; they never replace the token layer.
import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.105.0';
const db=createClient('https://zeyvkuhqgbqjqalxubrq.supabase.co','sb_publishable_trF3YpEfBC7rMZpxs0lzzg_utxyNU7t');
const $=id=>document.getElementById(id),world=$('world'),grid=$('gridLayer'),sidebar=document.querySelector('.left-panel');
const layer=document.createElement('div');layer.id='modularSceneLayer';layer.style.cssText='position:absolute;inset:0;pointer-events:none;z-index:1;';world.insertBefore(layer,grid);
const panel=document.createElement('section');panel.id='modularSceneEditor';panel.innerHTML=`<div class="divider"></div><div class="panel-title">MODULAR SCENE BUILDER</div><p class="small">Build connected rooms and corridors in grid squares. Each module can be edited independently; all players see the same layout.</p><label>MODULE<select id="moduleSelect" style="display:block;width:100%;margin-top:6px;background:#03080d;color:#d8edf5;padding:9px"><option value="">NEW MODULE</option></select></label><label>NAME<input id="moduleName" maxlength="64" value="Room"></label><label>TYPE<select id="moduleType" style="display:block;width:100%;margin-top:6px;background:#03080d;color:#d8edf5;padding:9px"><option value="room">ROOM</option><option value="corridor">CORRIDOR</option></select></label><label>LEFT (SQUARES)<input id="moduleX" type="number" min="0" max="499" step="1" value="0"></label><label>TOP (SQUARES)<input id="moduleY" type="number" min="0" max="499" step="1" value="0"></label><label>WIDTH (SQUARES)<input id="moduleW" type="number" min="1" max="500" step="1" value="8"></label><label>HEIGHT (SQUARES)<input id="moduleH" type="number" min="1" max="500" step="1" value="6"></label><button id="moduleSave" type="button">SAVE MODULE</button><button id="moduleDelete" type="button" class="secondary">DELETE SELECTED</button><div id="moduleStatus" class="message" role="status" aria-live="polite"></div>`;sidebar.append(panel);
let scene=null,session=null,channel=null,modules=[],busy=false,sequence=0;const gm=()=>$('roleLabel').textContent.trim().toLowerCase()==='gm',visible=()=>!$('tableView').classList.contains('hidden');const message=s=>$('moduleStatus').textContent=s;
const valid=m=>m&&typeof m.id==='string'&&['room','corridor'].includes(m.type)&&[m.x,m.y,m.w,m.h].every(Number.isInteger)&&m.x>=0&&m.y>=0&&m.w>0&&m.h>0&&m.x+m.w<=500&&m.y+m.h<=500;
function draw(){layer.replaceChildren();if(!scene)return;const size=Number(scene.grid_size)||64;for(const m of modules.filter(valid)){const tile=document.createElement('div');tile.dataset.moduleId=m.id;tile.title=m.name||m.type;tile.style.cssText=`position:absolute;left:${m.x*size}px;top:${m.y*size}px;width:${m.w*size}px;height:${m.h*size}px;box-sizing:border-box;border:${m.type==='room'?'4px solid #72a9b7':'2px dashed #a9b7ba'};background:${m.type==='room'?'#173442bb':'#39484b99'};pointer-events:none;`;const label=document.createElement('span');label.textContent=m.name||m.type;label.style.cssText='position:absolute;top:4px;left:5px;padding:2px 5px;background:#061019dd;color:#d8edf5;font:10px monospace;max-width:90%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;';tile.append(label);layer.append(tile);}}
function options(){const select=$('moduleSelect'),previous=select.value;select.replaceChildren(new Option('NEW MODULE',''));for(const m of modules)if(valid(m))select.add(new Option(`${m.name||m.type} (${m.x},${m.y})`,m.id));if(modules.some(m=>m.id===previous))select.value=previous;}
function fill(m){$('moduleName').value=m?.name||'Room';$('moduleType').value=m?.type||'room';for(const [key,id,fallback] of [['x','moduleX',0],['y','moduleY',0],['w','moduleW',8],['h','moduleH',6]])$(id).value=m?.[key]??fallback;}
$('moduleSelect').addEventListener('change',()=>fill(modules.find(m=>m.id===$('moduleSelect').value)));
function read(){const m={id:$('moduleSelect').value||crypto.randomUUID(),name:$('moduleName').value.trim().slice(0,64)||'Room',type:$('moduleType').value,x:Number($('moduleX').value),y:Number($('moduleY').value),w:Number($('moduleW').value),h:Number($('moduleH').value)};if(!valid(m))throw Error('Use whole-square coordinates within a 500 × 500 scene.');if(m.x+m.w>Number(scene.grid_cols)||m.y+m.h>Number(scene.grid_rows))throw Error('Module extends outside the playable grid. Expand the grid first.');return m;}
async function save(next){if(busy||!scene||!gm())return;busy=true;$('moduleSave').disabled=true;$('moduleDelete').disabled=true;try{const {data,error}=await db.from('scenes').update({map_modules:next}).eq('id',scene.id).select('map_modules').single();if(error||!data)throw error||Error('Permission denied');modules=Array.isArray(data.map_modules)?data.map_modules:[];options();draw();message('Modular layout saved for everyone.');}catch(e){message('Could not save: '+e.message);}finally{busy=false;$('moduleSave').disabled=false;$('moduleDelete').disabled=false;}}
$('moduleSave').addEventListener('click',()=>{try{const m=read();save([...modules.filter(item=>item.id!==m.id),m]).then(()=>{$('moduleSelect').value=m.id;});}catch(e){message(e.message);}});
$('moduleDelete').addEventListener('click',()=>{const id=$('moduleSelect').value;if(!id)return message('Select a module to delete.');if(!confirm('Delete this room or corridor?'))return;save(modules.filter(m=>m.id!==id)).then(()=>{$('moduleSelect').value='';fill(null);});});
async function load(){const serial=++sequence;if(!visible()||!$('codeLabel').textContent.trim()){panel.style.display='none';layer.replaceChildren();scene=null;session=null;if(channel){db.removeChannel(channel);channel=null;}return;}const code=$('codeLabel').textContent.trim();const {data:sessions,error}=await db.from('game_sessions').select('id,campaign_id').eq('join_code',code).eq('is_active',true);if(error)return;const {data:{user}}=await db.auth.getUser();if(!user)return;let active=null;for(const s of sessions||[]){const {data:member}=await db.from('campaign_members').select('role').eq('campaign_id',s.campaign_id).eq('user_id',user.id).maybeSingle();if(member){active=s;break;}}if(!active||serial!==sequence)return;const {data:scenes}=await db.from('scenes').select('id,grid_cols,grid_rows,grid_size,map_modules').eq('session_id',active.id).eq('is_active',true).order('sort_order').limit(1);if(!scenes?.length||serial!==sequence)return;const next=scenes[0];if(scene?.id!==next.id){if(channel)db.removeChannel(channel);channel=db.channel('modular-layout:'+next.id).on('postgres_changes',{event:'UPDATE',schema:'public',table:'scenes',filter:`id=eq.${next.id}`},async()=>{const {data}=await db.from('scenes').select('id,grid_cols,grid_rows,grid_size,map_modules').eq('id',next.id).single();if(data&&scene?.id===data.id){scene=data;modules=Array.isArray(data.map_modules)?data.map_modules:[];options();draw();}}).subscribe();}scene=next;session=active.id;modules=Array.isArray(next.map_modules)?next.map_modules:[];panel.style.display=gm()?'':'none';options();draw();}
const observer=new MutationObserver(()=>load().catch(e=>message(e.message)));observer.observe($('tableView'),{attributes:true,attributeFilter:['class']});observer.observe($('codeLabel'),{childList:true,characterData:true,subtree:true});observer.observe($('roleLabel'),{childList:true,characterData:true,subtree:true});panel.style.display='none';load().catch(console.error);
