// v0.5.2 Session Import & Manifest Builder. GM-only, client-side DOCX/TXT/MD extraction; saves reviewable draft to the active game session.
import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.105.0';
const db=createClient('https://zeyvkuhqgbqjqalxubrq.supabase.co','sb_publishable_trF3YpEfBC7rMZpxs0lzzg_utxyNU7t');
const role=document.getElementById('roleLabel'),table=document.getElementById('tableView'),codeEl=document.getElementById('codeLabel'),sidebar=document.querySelector('.left-panel');
const panel=document.createElement('section');panel.id='sessionImportPanel';panel.innerHTML=`<div class="divider"></div><div class="panel-title">SESSION IMPORT</div><p class="small">Drop a session document here. Nothing is deployed until you approve the manifest.</p><button id="sessionImportOpen" type="button">IMPORT SESSION</button><div id="sessionImportSummary" class="small">No manifest loaded.</div>`;sidebar.append(panel);
const modal=document.createElement('div');modal.id='sessionImportModal';modal.hidden=true;modal.innerHTML=`<div class="session-import-shell"><div class="session-import-head"><div><div class="eyebrow">DESTINY // SESSION INGEST</div><h2>SESSION MANIFEST</h2></div><button id="sessionImportClose" class="ghost">CLOSE</button></div><div id="sessionDrop" class="session-drop" tabindex="0"><strong>DROP SESSION DOCUMENT</strong><span>DOCX, TXT, or Markdown · 10 MB max</span><input id="sessionFile" type="file" accept=".docx,.txt,.md,text/plain,text/markdown,application/vnd.openxmlformats-officedocument.wordprocessingml.document" hidden></div><div id="sessionImportStatus" class="message"></div><div id="manifestEditor" hidden><div class="manifest-meta"><label>SESSION TITLE<input id="manifestTitle" maxlength="160"></label><label>SOURCE<input id="manifestSource" readonly></label></div><div class="manifest-columns manifest-three"><section><div class="panel-title">SCENES / LOCATIONS</div><div id="manifestScenes"></div><button id="addManifestScene" class="secondary">+ ADD SCENE</button></section><section><div class="panel-title">NAMED NPCs / CREATURES</div><div id="manifestNpcs"></div><button id="addManifestNpc" class="secondary">+ ADD NPC</button></section><section><div class="panel-title">ENCOUNTER ASSETS</div><div id="manifestEncounters"></div><button id="addManifestEncounter" class="secondary">+ ADD ENCOUNTER ASSET</button></section></div><label>IMPORT NOTES<textarea id="manifestNotes" rows="5" placeholder="GM notes or corrections before generation"></textarea></label><div class="manifest-actions"><button id="saveManifest" class="secondary">SAVE DRAFT</button><button id="approveManifest">APPROVE MANIFEST</button></div><p class="small">Approval freezes this draft as the instruction set for the next generation/deployment stage. It does not generate art or alter the map yet.</p></div></div>`;document.body.append(modal);
const $=id=>document.getElementById(id);let session=null,manifest=null,mammothPromise=null;
const gm=()=>role.textContent.trim().toLowerCase()==='gm'&&!table.classList.contains('hidden');
function visible(){panel.style.display=gm()?'':'none';if(!gm())modal.hidden=true}
new MutationObserver(visible).observe(role,{childList:true,subtree:true,characterData:true});new MutationObserver(visible).observe(table,{attributes:true,attributeFilter:['class']});visible();
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function activeSession(){const code=codeEl.textContent.trim();if(!code||code==='—')return null;const {data,error}=await db.from('game_sessions').select('id,name,session_manifest,session_source_name,session_manifest_status').eq('join_code',code).eq('is_active',true).maybeSingle();if(error)throw error;return data}
function loadMammoth(){if(window.mammoth)return Promise.resolve(window.mammoth);if(mammothPromise)return mammothPromise;mammothPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/mammoth@1.9.1/mammoth.browser.min.js';s.onload=()=>resolve(window.mammoth);s.onerror=()=>reject(Error('DOCX reader could not load.'));document.head.append(s)});return mammothPromise}
function clean(s){return String(s||'').replace(/\u00a0/g,' ').replace(/[ \t]+/g,' ').trim()}
function unique(arr){const seen=new Set();return arr.filter(x=>{const k=x.toLowerCase();if(!x||seen.has(k))return false;seen.add(k);return true})}
function parseHtml(html,fileName){const doc=new DOMParser().parseFromString(html,'text/html'),blocks=[];for(const el of doc.body.querySelectorAll('h1,h2,h3,h4,p,li,tr')){if(el.closest('tr')&&el.tagName.toLowerCase()!=='tr')continue;const text=clean(el.textContent);if(!text)continue;if(el.tagName.toLowerCase()==='tr'){const cells=[...el.querySelectorAll(':scope>td,:scope>th')].map(x=>clean(x.textContent)).filter(Boolean);blocks.push({tag:'tr',text,cells})}else blocks.push({tag:el.tagName.toLowerCase(),text})}return buildManifest(blocks,fileName)}
function parseText(text,fileName){const lines=String(text).split(/\r?\n/).map(clean).filter(Boolean),blocks=lines.map((text,i)=>({tag:/^(#{1,4})\s+/.test(text)?'h'+Math.min(4,RegExp.$1.length):(/^((act|scene|encounter|location|room|area|chapter|part)\b)/i.test(text)?'h2':'p'),text:text.replace(/^#{1,4}\s+/,'')}));return buildManifest(blocks,fileName)}
function npcRole(text=''){if(/wookiee|champion|bruiser|recruit/i.test(text))return 'Ally';if(/hutt|slaveholder|poisoner|enemy|gunslinger|guard|fighter|combatant|adversar/i.test(text))return 'Enemy';if(/creature|beast|acklay/i.test(text))return 'Creature';return 'NPC'}
function npcKey(name=''){return clean(name).toLowerCase().replace(/[’']/g,"'")}
function buildManifest(blocks,fileName){
 const headings=blocks.filter(b=>/^h[1-4]$/.test(b.tag)),title=headings[0]?.text||fileName.replace(/\.[^.]+$/,'');
 const sceneRx=/\b(scene|encounter|location|room|area|chamber|corridor|hangar|dock|cantina|temple|ruins|base|spaceport|pit|audience|act|chapter|part|match)\b/i;
 let scenes=unique(headings.filter(h=>sceneRx.test(h.text)).map(h=>h.text)).slice(0,40);if(!scenes.length)scenes=unique(headings.slice(1).map(h=>h.text)).slice(0,20);
 const found=new Map(),encounters=new Map();
 const addEncounter=(name,cl=null,quantity=1,description='',source='Stat block')=>{name=clean(name);if(!name)return;const k=npcKey(name);const prev=encounters.get(k);encounters.set(k,{name,cl:cl?Number(cl):null,quantity:Math.max(1,Number(quantity)||1),role:/creature|beast|acklay/i.test(name+' '+description)?'Creature':'Enemy',portraitNeeded:false,hiddenFromPC:true,notes:clean(description),source:prev?.source||source})};
 const addNpc=(name,description='',source='document')=>{name=clean(name).replace(/\s+[—–-]\s*x?\d+$/i,'').replace(/\s*\(CL\s*\d+\)\s*$/i,'');description=clean(description);if(!name||name.length>80)return;const bad=/^(important npcs?|critical dcs?|suggested awards?|damage|speed|defenses|abilities|feats|talents|tactics|init|hp|melee|ranged|unarmed|attack|skills|species|languages|base atk|condition|duration|round \d|day \d|night \d|objective|failure|outcome|creature|role|requirement|majordomo)$/i;if(bad.test(name))return;const k=npcKey(name),prev=found.get(k);if(!prev||source==='Important NPCs')found.set(k,{name,role:npcRole(name+' '+description),portraitNeeded:true,hiddenFromPC:false,notes:description,source})};
 // Highest-confidence source: authored Important NPCs quick-reference/table.
 for(let i=0;i<blocks.length;i++){if(!/^important npcs?$/i.test(blocks[i].text))continue;for(let j=i+1;j<blocks.length;j++){const b=blocks[j];if(b.tag==='tr'&&b.cells?.length>=2){addNpc(b.cells[0],b.cells.slice(1).join(' '),'Important NPCs');continue}if(/^h[1-4]$/.test(b.tag)||b.tag==='tr')break}}
 // Named stat blocks are strong evidence too; generic encounter packages remain encounter assets, not portrait NPCs.
 const generic=/\b(generic|nonheroic|heroic gladiator|arena fighter|tournament fighter|compound guard|security|forced combatant|pit fighter)\b/i;
 for(const b of blocks){const m=b.text.match(/^(.{2,70}?)\s*\(CL\s*(\d+)\)(?:\s*[—–-]\s*x?(\d+))?$/i);if(!m)continue;if(generic.test(m[1]))addEncounter(m[1],m[2],m[3]||1,'Generic combat/stat-block package');else addNpc(m[1],'Named stat block','Stat block')}
 // Capture authored two-column identity rows such as Majordomo | Hulfeji Tonku, ...
 for(const b of blocks){if(b.tag!=='tr'||!b.cells||b.cells.length<2)continue;const label=b.cells[0],desc=b.cells.slice(1).join(' ');if(/^(majordomo|champion|contact|employer|handler|master|villain|ally|recruit)$/i.test(label)){const m=desc.match(/^([A-Z][\p{L}’'\-]+(?:\s+[A-Z][\p{L}’'\-]+){0,3})(?:,|\s+(?:the|a|an)\b)/u);if(m)addNpc(m[1],desc,'Identity row')}}
 return {version:3,title,source:fileName,createdAt:new Date().toISOString(),scenes:scenes.map(name=>({name,visualPrompt:'',hiddenFromPC:false,notes:''})),npcs:[...found.values()].slice(0,50),encounterAssets:[...encounters.values()].slice(0,80),notes:'',sourceOutline:headings.slice(0,80).map(h=>h.text)}
}
function sceneRow(s={name:'',visualPrompt:'',hiddenFromPC:false,notes:''}){const d=document.createElement('div');d.className='manifest-card';d.innerHTML=`<button class="manifest-remove" title="Remove">×</button><label>NAME<input data-k="name" value="${esc(s.name)}"></label><label>VISUAL / MAP PROMPT<textarea data-k="visualPrompt" rows="2">${esc(s.visualPrompt)}</textarea></label><label class="manifest-check"><input data-k="hiddenFromPC" type="checkbox" ${s.hiddenFromPC?'checked':''}> START HIDDEN FROM PCs</label><label>NOTES<textarea data-k="notes" rows="2">${esc(s.notes)}</textarea></label>`;d.querySelector('.manifest-remove').onclick=()=>d.remove();return d}
function npcRow(n={name:'',role:'NPC',portraitNeeded:true,hiddenFromPC:false,notes:''}){const d=document.createElement('div');d.className='manifest-card';d.innerHTML=`<button class="manifest-remove" title="Remove">×</button><label>NAME<input data-k="name" value="${esc(n.name)}"></label><label>ROLE<select data-k="role"><option>NPC</option><option>Ally</option><option>Enemy</option><option>Creature</option><option>PC</option></select></label><label class="manifest-check"><input data-k="portraitNeeded" type="checkbox" ${n.portraitNeeded!==false?'checked':''}> PORTRAIT NEEDED</label><label class="manifest-check"><input data-k="hiddenFromPC" type="checkbox" ${n.hiddenFromPC?'checked':''}> START HIDDEN FROM PCs</label><label>NOTES<textarea data-k="notes" rows="2">${esc(n.notes)}</textarea></label>`;d.querySelector('[data-k="role"]').value=n.role||'NPC';d.querySelector('.manifest-remove').onclick=()=>d.remove();return d}
function encounterRow(e={name:'',cl:null,quantity:1,role:'Enemy',portraitNeeded:false,hiddenFromPC:true,notes:''}){const d=document.createElement('div');d.className='manifest-card encounter-card';d.innerHTML=`<button class="manifest-remove" title="Remove">×</button><label>ASSET<input data-k="name" value="${esc(e.name)}"></label><div class="manifest-pair"><label>CL<input data-k="cl" type="number" min="0" max="30" value="${e.cl??''}"></label><label>DEFAULT QTY<input data-k="quantity" type="number" min="1" max="50" value="${e.quantity||1}"></label></div><label>ROLE<select data-k="role"><option>Enemy</option><option>Creature</option><option>Ally</option><option>NPC</option></select></label><label class="manifest-check"><input data-k="portraitNeeded" type="checkbox" ${e.portraitNeeded?'checked':''}> UNIQUE PORTRAIT NEEDED</label><label class="manifest-check"><input data-k="hiddenFromPC" type="checkbox" ${e.hiddenFromPC!==false?'checked':''}> START HIDDEN FROM PCs</label><label>NOTES<textarea data-k="notes" rows="2">${esc(e.notes)}</textarea></label>`;d.querySelector('[data-k="role"]').value=e.role||'Enemy';d.querySelector('.manifest-remove').onclick=()=>d.remove();return d}

function render(m){manifest=m;$('manifestTitle').value=m.title||'';$('manifestSource').value=m.source||'';$('manifestNotes').value=m.notes||'';$('manifestScenes').replaceChildren(...(m.scenes||[]).map(sceneRow));$('manifestNpcs').replaceChildren(...(m.npcs||[]).map(npcRow));$('manifestEncounters').replaceChildren(...(m.encounterAssets||[]).map(encounterRow));$('manifestEditor').hidden=false;$('sessionImportSummary').textContent=`${m.scenes?.length||0} scenes · ${m.npcs?.length||0} NPCs · ${m.encounterAssets?.length||0} encounter assets · ${session?.session_manifest_status||'unsaved'}`}
function collect(){const rows=(id,keys)=>[...$(id).children].map(card=>Object.fromEntries(keys.map(k=>{const el=card.querySelector(`[data-k="${k}"]`);return [k,el?.type==='checkbox'?el.checked:clean(el?.value)]})));return {...manifest,title:clean($('manifestTitle').value)||'Untitled Session',source:$('manifestSource').value,notes:$('manifestNotes').value,scenes:rows('manifestScenes',['name','visualPrompt','hiddenFromPC','notes']).filter(x=>x.name),npcs:rows('manifestNpcs',['name','role','portraitNeeded','hiddenFromPC','notes']).filter(x=>x.name),encounterAssets:rows('manifestEncounters',['name','cl','quantity','role','portraitNeeded','hiddenFromPC','notes']).filter(x=>x.name).map(x=>({...x,cl:x.cl===''?null:Number(x.cl),quantity:Math.max(1,Number(x.quantity)||1)})),updatedAt:new Date().toISOString()}}
async function persist(status){manifest=collect();$('sessionImportStatus').textContent=status==='approved'?'Approving manifest…':'Saving draft…';const {data,error}=await db.from('game_sessions').update({session_manifest:manifest,session_source_name:manifest.source,session_manifest_status:status}).eq('id',session.id).select('session_manifest_status').single();if(error)throw error;session.session_manifest_status=data.session_manifest_status;$('sessionImportStatus').textContent=status==='approved'?'Manifest approved. Ready for the generation/deployment stage.':'Draft saved.';$('sessionImportSummary').textContent=`${manifest.scenes.length} scenes · ${manifest.npcs.length} NPCs · ${manifest.encounterAssets?.length||0} encounter assets · ${status}`}
async function open(){if(!gm())return;try{session=await activeSession();if(!session)throw Error('Active session not found.');modal.hidden=false;if(session.session_manifest){render(session.session_manifest);$('sessionImportStatus').textContent=`Loaded ${session.session_manifest_status} manifest.`}}catch(e){$('sessionImportStatus').textContent=e.message}}
$('sessionImportOpen').onclick=open;$('sessionImportClose').onclick=()=>modal.hidden=true;$('sessionDrop').onclick=()=>$('sessionFile').click();$('sessionDrop').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('sessionFile').click()}};
for(const ev of ['dragenter','dragover'])$('sessionDrop').addEventListener(ev,e=>{e.preventDefault();$('sessionDrop').classList.add('dragging')});for(const ev of ['dragleave','drop'])$('sessionDrop').addEventListener(ev,e=>{$('sessionDrop').classList.remove('dragging')});$('sessionDrop').addEventListener('drop',e=>{e.preventDefault();handle(e.dataTransfer.files?.[0])});$('sessionFile').onchange=()=>{handle($('sessionFile').files?.[0]);$('sessionFile').value=''};
async function handle(file){if(!file)return;if(file.size>10*1024*1024){$('sessionImportStatus').textContent='File exceeds 10 MB.';return}try{$('sessionImportStatus').textContent='Reading '+file.name+'…';let m;if(/\.docx$/i.test(file.name)){const mammoth=await loadMammoth(),result=await mammoth.convertToHtml({arrayBuffer:await file.arrayBuffer()});m=parseHtml(result.value,file.name);if(result.messages?.length)$('sessionImportStatus').textContent='Document read with '+result.messages.length+' conversion note(s). Review the manifest.';}else if(/\.(txt|md)$/i.test(file.name)||file.type.startsWith('text/'))m=parseText(await file.text(),file.name);else throw Error('Use DOCX, TXT, or Markdown.');render(m);$('sessionImportStatus').textContent=`Extracted ${m.scenes.length} scene candidates, ${m.npcs.length} named NPCs, and ${m.encounterAssets?.length||0} encounter assets. Review before approval.`}catch(e){$('sessionImportStatus').textContent='Import failed: '+e.message}}
$('addManifestScene').onclick=()=>{$('manifestScenes').append(sceneRow());$('manifestScenes').lastElementChild.querySelector('input').focus()};$('addManifestNpc').onclick=()=>{$('manifestNpcs').append(npcRow());$('manifestNpcs').lastElementChild.querySelector('input').focus()};$('addManifestEncounter').onclick=()=>{$('manifestEncounters').append(encounterRow());$('manifestEncounters').lastElementChild.querySelector('input').focus()};$('saveManifest').onclick=()=>persist('draft').catch(e=>$('sessionImportStatus').textContent='Save failed: '+e.message);$('approveManifest').onclick=()=>persist('approved').catch(e=>$('sessionImportStatus').textContent='Approval failed: '+e.message);
