// GM-only token footprint controls. Uses the existing scene_tokens size_squares column.
import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.105.0';
const supabase=createClient('https://zeyvkuhqgbqjqalxubrq.supabase.co','sb_publishable_trF3YpEfBC7rMZpxs0lzzg_utxyNU7t');
const list=document.getElementById('tokenList'),layer=document.getElementById('tokenLayer'),role=document.getElementById('roleLabel');
const panel=document.createElement('section');panel.className='token-size-panel';panel.innerHTML='<div class="panel-title">TOKEN FOOTPRINT · GM</div><label for="sizeToken">TOKEN</label><select id="sizeToken"><option value="">Select a token</option></select><label for="sizeSquares">SIZE</label><select id="sizeSquares"><option value="1">Medium / Small · 1 × 1</option><option value="2">Large · 2 × 2</option><option value="3">Huge · 3 × 3</option><option value="4">Gargantuan · 4 × 4</option><option value="6">Colossal · 6 × 6</option></select><button type="button" id="saveTokenSize">SAVE TOKEN SIZE</button><div id="sizeMessage" role="status" aria-live="polite"></div>';
list.parentElement.appendChild(panel);
const tokenSelect=panel.querySelector('#sizeToken'),sizeSelect=panel.querySelector('#sizeSquares'),save=panel.querySelector('#saveTokenSize'),message=panel.querySelector('#sizeMessage');
const gm=()=>role.textContent.trim().toLowerCase()==='gm';
function tokens(){return [...layer.querySelectorAll('.token[data-id]')].map(el=>({id:el.dataset.id,label:el.querySelector('.token-name')?.textContent||el.dataset.id,el}));}
function sync(){panel.hidden=!gm();if(!gm())return;const current=tokenSelect.value,entries=tokens();if(entries.length===tokenSelect.options.length-1&&entries.every((t,i)=>tokenSelect.options[i+1]?.value===t.id))return;tokenSelect.replaceChildren(new Option('Select a token',''));for(const t of entries)tokenSelect.add(new Option(t.label,t.id));if(entries.some(t=>t.id===current))tokenSelect.value=current;else {sizeSelect.value='1';message.textContent='';}}
const observer=new MutationObserver(sync);observer.observe(layer,{childList:true});observer.observe(role,{childList:true,characterData:true,subtree:true});sync();
function sceneGrid(){const size=parseFloat(getComputedStyle(document.getElementById('gridLayer')).backgroundSize)||64;const world=document.getElementById('world');return {cols:Math.round(world.offsetWidth/size),rows:Math.round(world.offsetHeight/size)};}
tokenSelect.addEventListener('change',async()=>{message.textContent='';if(!tokenSelect.value)return;const {data,error}=await supabase.from('scene_tokens').select('size_squares').eq('id',tokenSelect.value).single();if(error){message.textContent=error.message;return;}sizeSelect.value=String(data.size_squares);if(sizeSelect.selectedIndex<0)message.textContent='Custom size: choose a listed footprint to change it.';});
// Clicking a token selects it for editing without changing its drag behavior.
layer.addEventListener('pointerdown',e=>{if(!gm())return;const token=e.target.closest('.token[data-id]');if(token){tokenSelect.value=token.dataset.id;tokenSelect.dispatchEvent(new Event('change'));}},true);
save.addEventListener('click',async()=>{if(!gm()||!tokenSelect.value)return;const id=tokenSelect.value,size=Number(sizeSelect.value);if(![1,2,3,4,6].includes(size))return;save.disabled=true;message.textContent='Saving…';try{const {data:token,error:readError}=await supabase.from('scene_tokens').select('id,label,x,y,scene_id').eq('id',id).single();if(readError)throw readError;const grid=sceneGrid();if(size>grid.cols||size>grid.rows)throw new Error('Footprint exceeds the map.');const x=Math.min(Number(token.x),grid.cols-size),y=Math.min(Number(token.y),grid.rows-size);const {data,error}=await supabase.from('scene_tokens').update({size_squares:size,x,y}).eq('id',id).select('id,size_squares').single();if(error)throw error;if(!data)throw new Error('No token was updated.');message.textContent=`${token.label}: ${size} × ${size} squares saved.`;}catch(error){message.textContent=`Unable to save: ${error.message}`;}finally{save.disabled=false;}});
