// GM-only independent token creation. Console dossier imports use the existing Console -> bridge path.
import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.105.0';
const db=createClient('https://zeyvkuhqgbqjqalxubrq.supabase.co','sb_publishable_trF3YpEfBC7rMZpxs0lzzg_utxyNU7t');
const role=document.getElementById('roleLabel'),layer=document.getElementById('tokenLayer'),list=document.getElementById('tokenList'),grid=document.getElementById('gridLabel'),table=document.getElementById('tableView');
const panel=document.createElement('section');panel.id='tokenAddPanel';panel.hidden=true;
panel.innerHTML=`<div class="panel-title">ADD TOKEN</div><button type="button" id="tokenAddToggle" aria-expanded="false">+ ADD TOKEN</button><div id="tokenAddBody" hidden><div class="token-add-tabs"><button type="button" id="tokenManualTab" aria-pressed="true">MANUAL</button><button type="button" id="tokenDossierTab" aria-pressed="false">CONSOLE DOSSIER</button></div><form id="tokenAddForm"><label>NAME <input name="name" maxlength="120" required placeholder="Character or enemy name"></label><label>TYPE <select name="kind"><option value="enemy">Enemy</option><option value="ally">Ally</option><option value="pc">Player character</option><option value="neutral">Neutral</option></select></label><div class="token-add-grid"><label>MAP COLUMN <input name="x" type="number" min="1" step="1" required></label><label>MAP ROW <input name="y" type="number" min="1" step="1" required></label><label>SIZE (SQUARES) <input name="size" type="number" min="1" max="10" step="1" value="1" required></label><label>INITIATIVE <input name="initiative" type="number" step="1" placeholder="Optional"></label><label>CURRENT HP <input name="hp" type="number" min="0" step="1" placeholder="Optional"></label><label>MAX HP <input name="max" type="number" min="0" step="1" placeholder="Optional"></label></div><label>CONDITION <select name="condition"><option value="0">Normal</option><option value="-1">−1 step</option><option value="-2">−2 steps</option><option value="-3">−3 steps</option><option value="-4">−4 steps</option><option value="-5">Helpless</option></select></label><button type="submit" id="tokenAddSave">PLACE TOKEN</button></form><div id="tokenDossierHelp" hidden><p>Open the Command Console, choose the NPC or character in its Tactical Dossier, and use <strong>ADD TO INITIATIVE</strong>. With Tactical Table Link signed in and sync enabled, the bridge imports its name, HP, initiative and conditions to this scene. You can then drag the new token to its map position.</p><p>Do not import the same dossier twice. If a matching token is already here, the bridge will update it or stop on an ambiguous match instead of silently duplicating it.</p><p>The Console remains local: this website cannot read its private dossier database directly. If the Console is unavailable, use MANUAL above.</p></div><div id="tokenAddMessage" role="status" aria-live="polite"></div></div>`;
list.parentElement.insertBefore(panel,list);
const style=document.createElement('style');style.textContent=`#tokenAddPanel{margin:10px 0;padding:10px;border:1px solid #477d9a;border-radius:8px;background:rgba(18,54,74,.35)}#tokenAddPanel[hidden],#tokenAddBody[hidden],#tokenDossierHelp[hidden],#tokenAddForm[hidden]{display:none!important}#tokenAddPanel button{max-width:100%;white-space:normal}#tokenAddPanel label{display:block;margin:8px 0;font-size:11px}#tokenAddPanel input,#tokenAddPanel select{box-sizing:border-box;width:100%;min-width:0;margin-top:4px}#tokenAddPanel .token-add-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 8px}#tokenAddPanel .token-add-tabs{display:flex;gap:6px;margin:10px 0}#tokenAddPanel .token-add-tabs button{flex:1;font-size:11px}#tokenAddMessage{margin-top:8px;font-size:12px;overflow-wrap:anywhere}`;document.head.appendChild(style);
const $=id=>panel.querySelector('#'+id),form=$('tokenAddForm'),message=$('tokenAddMessage');let busy=false;
function gm(){return role.textContent.trim().toLowerCase()==='gm'&&!table.classList.contains('hidden')}
function visibility(){panel.hidden=!gm()}
new MutationObserver(visibility).observe(role,{childList:true,subtree:true,characterData:true});new MutationObserver(visibility).observe(table,{attributes:true,attributeFilter:['class']});visibility();
$('tokenAddToggle').onclick=()=>{const open=$('tokenAddBody').hidden;$('tokenAddBody').hidden=!open;$('tokenAddToggle').setAttribute('aria-expanded',String(open));if(open)chooseCell()};
function tab(dossier){form.hidden=dossier;$('tokenDossierHelp').hidden=!dossier;$('tokenManualTab').setAttribute('aria-pressed',String(!dossier));$('tokenDossierTab').setAttribute('aria-pressed',String(dossier));message.textContent=''}
$('tokenManualTab').onclick=()=>tab(false);$('tokenDossierTab').onclick=()=>tab(true);
function dimensions(){const match=grid.textContent.match(/(\d+)\s*[×x]\s*(\d+)/);return match?[Number(match[1]),Number(match[2])]:[0,0]}
function chooseCell(){const [cols,rows]=dimensions();if(!cols||!rows)return;const used=new Set([...layer.querySelectorAll('.token[data-id]')].map(el=>`${Math.round((parseFloat(el.style.left)-4)/(parseFloat(getComputedStyle(document.getElementById('gridLayer')).backgroundSize)||64))},${Math.round((parseFloat(el.style.top)-4)/(parseFloat(getComputedStyle(document.getElementById('gridLayer')).backgroundSize)||64))}`));for(let y=0;y<rows;y++)for(let x=0;x<cols;x++)if(!used.has(`${x},${y}`)){form.elements.x.value=x+1;form.elements.y.value=y+1;return}form.elements.x.value=1;form.elements.y.value=1}
function optionalInt(value){if(value.trim()==='')return null;const n=Number(value);if(!Number.isSafeInteger(n))throw Error('Initiative and HP must be whole numbers.');return n}
form.addEventListener('submit',async event=>{event.preventDefault();if(!gm()||busy)return;const f=form.elements,[cols,rows]=dimensions(),name=f.name.value.trim(),x=Number(f.x.value)-1,y=Number(f.y.value)-1,size=Number(f.size.value);if(!name||name.length>120||!cols||!rows||![x,y,size].every(Number.isSafeInteger)||x<0||y<0||size<1||size>10||x+size>cols||y+size>rows){message.textContent='Enter a name and a valid map position and size.';return}let initiative,hp,max;try{initiative=optionalInt(f.initiative.value);hp=optionalInt(f.hp.value);max=optionalInt(f.max.value);if(hp!==null&&hp<0||max!==null&&max<0||hp!==null&&max!==null&&hp>max)throw Error('HP must be nonnegative and current HP cannot exceed maximum HP.')}catch(error){message.textContent=error.message;return}const sceneId=await (async()=>{const {data,error}=await db.from('scenes').select('id').eq('is_active',true).in('session_id',(await db.from('game_sessions').select('id').eq('join_code',document.getElementById('codeLabel').textContent.trim())).data?.map(s=>s.id)||[]).limit(1);if(error)throw error;return data?.[0]?.id})();if(!sceneId){message.textContent='Active scene not found. Re-enter the session and try again.';return}busy=true;$('tokenAddSave').disabled=true;message.textContent='Placing token…';try{const state={initiative,hp,max_hp:max,condition_step:Number(f.condition.value)};const {data,error}=await db.from('scene_tokens').insert({scene_id:sceneId,label:name,kind:f.kind.value,x,y,size_squares:size,state}).select('id').single();if(error)throw error;if(!data)throw Error('Token creation was not permitted.');message.textContent=`${name} placed at ${x+1}, ${y+1}.`;form.reset();chooseCell()}catch(error){message.textContent=`ADD FAILED: ${error.message}`}finally{busy=false;$('tokenAddSave').disabled=false}});
